services:
  - type: web
    name: rentflow-api
    runtime: python
    plan: free
    rootDir: .
    buildCommand: pip install -r nomba/requirements.txt
    startCommand: uvicorn nomba.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        sync: false
      - key: NOMBA_PRIVATE_KEY
        sync: false
